/* Term 3 Quests — the build pool: 50 ideas the groups choose from.
   Each idea is only a name, the idea behind it and what the group ends up
   with; the plan, roles and checkpoints are worked out once a group picks. */
window.T3_POOL = [
  /* ---------- Science in action ---------- */
  { id: 'sci-breakfast', cat: 'sci', title: 'Breakfast machine',
    hook: 'Energy passes from one thing to the next: rolling, falling, toppling, lifting.',
    make: 'A chain-reaction contraption with at least 10 steps that starts with one marble and ends by pouring a bowl of cereal.' },
  { id: 'sci-claw', cat: 'sci', title: 'Hydraulic claw arcade game',
    hook: 'Water can’t be squashed, so a push on one syringe moves another at the end of a tube.',
    make: 'A playable claw machine in a box, worked by syringes of coloured water, that grabs prizes for visitors.' },
  { id: 'sci-pinball', cat: 'sci', title: 'Cardboard pinball table',
    hook: 'Angles, springs and slopes decide where a ball goes and how fast.',
    make: 'A full pinball table with a spring launcher, rubber-band flippers, bumpers, ramps and a working score board.' },
  { id: 'sci-automaton', cat: 'sci', title: 'Moving story automaton',
    hook: 'Cams, cranks and levers turn one turning handle into all kinds of movement.',
    make: 'A hand-cranked wooden or cardboard scene, like a fisherman casting or a dancer turning, where every figure moves.' },
  { id: 'sci-rocket', cat: 'sci', title: 'Water rocket launch programme',
    hook: 'Air pushes water out of the back, and the water pushes the rocket forwards.',
    make: 'Bottle rockets and a launch pad, tested launch after launch until one flies straight and lands furthest.' },
  { id: 'sci-bridge', cat: 'sci', title: 'Craft-stick bridge challenge',
    hook: 'Triangles can’t change shape, which is why real bridges are built from them.',
    make: 'A bridge of craft sticks and glue that spans a gap between two tables and holds a bucket of water many times its own weight.' },
  { id: 'sci-quake', cat: 'sci', title: 'Earthquake-proof city',
    hook: 'Buildings survive shaking when they are braced, balanced and anchored well.',
    make: 'A shake table and a model city of towers that stay standing while it shakes harder and harder.' },
  { id: 'sci-lander', cat: 'sci', title: 'Egg-drop Mars lander',
    hook: 'Slowing a fall gently spreads the force of landing over time.',
    make: 'A lander with parachute and crumple zone that drops from the first floor and lands a raw egg without a crack.' },
  { id: 'sci-kites', cat: 'sci', title: 'Kite workshop and flying day',
    hook: 'A kite flies when the wind pushes up on it more than gravity pulls it down.',
    make: 'Three different kites designed, built and tested, ending in a kite-flying day where the best design flies highest.' },
  { id: 'sci-vortex', cat: 'sci', title: 'Air vortex cannon range',
    hook: 'A sharp push of air rolls into a spinning ring that travels a long way.',
    make: 'A cannon that fires invisible rings of air across the room to knock down paper-cup towers, with a target range for visitors.' },
  { id: 'sci-lightmaze', cat: 'sci', title: 'Light maze',
    hook: 'Light bounces off a mirror at the same angle it hits it.',
    make: 'A dark maze box where players steer a torch beam with angled mirrors past obstacles to hit a target.' },
  { id: 'sci-camera', cat: 'sci', title: 'Walk-in pinhole camera',
    hook: 'Light travels in straight lines, so a tiny hole projects the world upside down.',
    make: 'A blacked-out box big enough to put your head and shoulders in, that shows the garden outside upside down on a screen.' },
  { id: 'sci-shadow', cat: 'sci', title: 'Shadow puppet theatre',
    hook: 'Shadows grow and shrink as objects move closer to or further from the light.',
    make: 'A shadow theatre with jointed puppets and sliding scenery, and a short show performed for the other groups.' },
  { id: 'sci-junkband', cat: 'sci', title: 'Junk band',
    hook: 'Every sound is a vibration; length, tightness and size change the note.',
    make: 'A set of tuned instruments from everyday things, like a rubber-band guitar, straw pan pipes and a water-bottle xylophone, played as a band.' },
  { id: 'sci-crane', cat: 'sci', title: 'Scrapyard magnet crane',
    hook: 'Electricity flowing through a coil of wire makes a magnet you can switch on and off.',
    make: 'A crane with a hand winch and a battery electromagnet that picks up and drops a load of paper clips on command.' },
  { id: 'sci-trebuchet', cat: 'sci', title: 'Trebuchet target challenge',
    hook: 'A falling weight swings an arm and flings a ball much further than a throw.',
    make: 'A tabletop trebuchet tuned to hit targets at different distances, every time.' },
  { id: 'sci-turbine', cat: 'sci', title: 'Wind turbine power station',
    hook: 'Blades turn the wind into spinning, and a motor turned backwards makes electricity.',
    make: 'A turbine with blades the group designs, that lights an LED in front of a fan and shows its voltage on a meter.' },
  { id: 'sci-waterwheel', cat: 'sci', title: 'Water wheel that does work',
    hook: 'Falling water has energy that a wheel can catch and use.',
    make: 'A water wheel under a running tap that winds up a string and lifts a small load, as heavy as it can manage.' },
  { id: 'sci-archimedes', cat: 'sci', title: 'Archimedes screw',
    hook: 'A turning spiral can carry water uphill, a trick over 2,000 years old.',
    make: 'A hand-turned screw made from clear tubing wound round a pole that lifts water from one tub to a higher one.' },
  { id: 'sci-orrery', cat: 'sci', title: 'Hand-cranked solar system',
    hook: 'Gears of different sizes turn at different speeds, like planets and moons.',
    make: 'A cardboard gear model where turning one handle moves the Earth round the Sun and the Moon round the Earth.' },
  { id: 'sci-dome', cat: 'sci', title: 'Newspaper dome planetarium',
    hook: 'A dome made of triangles is light but very strong.',
    make: 'A dome of rolled newspaper big enough for the group to sit inside, with a home-made star projector lighting up the ceiling.' },
  { id: 'sci-hand', cat: 'sci', title: 'Robotic hand',
    hook: 'Tendons pull on bones to bend fingers.',
    make: 'A life-size cardboard hand with string tendons and straw joints that bends each finger and can grip a cup.' },
  { id: 'sci-pendulum', cat: 'sci', title: 'Pendulum painting machine',
    hook: 'A swinging pendulum traces patterns that depend on its length and push.',
    make: 'A frame with a dripping paint pendulum that makes swirling patterns, and a gallery of the best ones.' },
  { id: 'sci-bubbles', cat: 'sci', title: 'Giant bubble lab',
    hook: 'A bubble is a thin skin of water held together by surface tension.',
    make: 'Tested bubble recipes and home-made giant wands, ending in a bubble show with bubbles big enough to stand inside.' },
  { id: 'sci-waterclock', cat: 'sci', title: 'Water clock',
    hook: 'Before clocks had springs, people measured time with dripping water.',
    make: 'A clock of stacked bottles that drips through and marks the minutes, tested against a stopwatch until it’s accurate.' },

  /* ---------- Solve a LifeHub problem ---------- */
  { id: 'sol-den', cat: 'sol', title: 'Bamboo reading den',
    hook: 'There is no quiet, shady spot outside to read, think or talk.',
    make: 'A bamboo den lashed together with rope, roofed with shade net, big enough for four Risers to sit inside.' },
  { id: 'sol-dryer', cat: 'sol', title: 'Solar food dryer',
    hook: 'Extra fruit and leaves go to waste, and drying them in the open brings dust and flies.',
    make: 'A sun-powered dryer box with mesh trays that dries fruit and curry leaves faster and cleaner than the open air.' },
  { id: 'sol-vgarden', cat: 'sol', title: 'Bottle tower garden',
    hook: 'There is little ground space to grow food, and pots get forgotten.',
    make: 'Bottle planters hung in columns that water each other from one bucket at the top, growing herbs and greens for the kitchen.' },
  { id: 'sol-weather', cat: 'sol', title: 'LifeHub weather station',
    hook: 'Watering the garden and going outdoors are decided by guessing the weather.',
    make: 'Home-made rain gauge, wind vane and wind meter, and a daily weather board that tells the garden team whether to water.' },
  { id: 'sol-ecobench', cat: 'sol', title: 'Ecobrick bench',
    hook: 'Snack wrappers and plastic bags pile up with nowhere to go.',
    make: 'Bottles packed hard with plastic waste, built into a mud-covered bench in the garden.' },
  { id: 'sol-steppingstones', cat: 'sol', title: 'Stepping-stone path',
    hook: 'One corner of the garden turns to mud every time it rains.',
    make: 'Hand-poured concrete stepping stones decorated with mosaic and handprints, laid as a path across the muddy patch.' },
  { id: 'sol-herbspiral', cat: 'sol', title: 'Herb spiral',
    hook: 'The kitchen buys herbs that could be grown right outside.',
    make: 'A raised spiral bed of bricks and soil with sunny dry herbs at the top and thirsty ones at the bottom.' },
  { id: 'sol-insecthotel', cat: 'sol', title: 'Insect hotel',
    hook: 'The garden needs bees, ladybirds and other helpers, but has nowhere for them to live.',
    make: 'A tall bug hotel of crates packed with bamboo, bricks, bark and pine cones, and a log of who moves in.' },
  { id: 'sol-birdscarer', cat: 'sol', title: 'Seedling guard',
    hook: 'Crows and squirrels dig up and eat the seedlings.',
    make: 'Moving, flashing, rattling bird scarers and seedling covers, tested to see which really keep the beds safe.' },
  { id: 'sol-birdcafe', cat: 'sol', title: 'Bird café',
    hook: 'In the hot months birds struggle to find water and food.',
    make: 'A bird feeder, water bowl and perch station placed where everyone can watch, and a bird-spotting chart of every visitor.' },
  { id: 'sol-compost', cat: 'sol', title: 'Snack-waste compost',
    hook: 'Fruit peels and leftovers go into the bin while the garden needs soil.',
    make: 'A compost bay with a worm bin that turns LifeHub’s food scraps into rich soil for the garden.' },
  { id: 'sol-mosquito', cat: 'sol', title: 'Mosquito patrol',
    hook: 'In the monsoon, mosquitoes breed in any water left standing.',
    make: 'A map of every place water collects at LifeHub, a fix for each one, and egg traps that show if the fixes are working.' },
  { id: 'sol-arcade', cat: 'sol', title: 'Cardboard arcade',
    hook: 'LifeHub events need something fun that also raises money.',
    make: 'An arcade of cardboard games, from basketball hoops to ball drops, with tickets and prizes, run at a LifeHub event.' },
  { id: 'sol-paper', cat: 'sol', title: 'Recycled paper studio',
    hook: 'Piles of used paper get thrown away every week.',
    make: 'Home-made frames and screens to turn waste paper into new sheets, made into LifeHub notebooks and cards.' },
  { id: 'sol-dye', cat: 'sol', title: 'Natural dye studio',
    hook: 'LifeHub has no team T-shirts for events and outings.',
    make: 'Dyes from turmeric, beetroot and onion skins, tested for colour and fastness, used to tie-dye a T-shirt for everyone.' },
  { id: 'sol-library', cat: 'sol', title: 'Little library',
    hook: 'Good books sit unread at home while others have run out of things to read.',
    make: 'A weatherproof book box with a door at the LifeHub entrance, and a simple borrow-and-return system.' },
  { id: 'sol-furniture', cat: 'sol', title: 'Cardboard furniture',
    hook: 'The reading corner needs more seats, and there is a pile of cardboard boxes.',
    make: 'Stools and a bench made only of cardboard and glue that are strong enough for an adult to sit on.' },
  { id: 'sol-hammock', cat: 'sol', title: 'Rope hammock',
    hook: 'There is nowhere to lie back and rest during a long day.',
    make: 'A hammock or hanging chair knotted from rope, strong enough to hold a grown-up, hung in a shady spot.' },
  { id: 'sol-obstacle', cat: 'sol', title: 'Recess obstacle course',
    hook: 'Recess games get repetitive and the same few things get played every day.',
    make: 'A course of tyres, crates, ropes and planks with a timed challenge everyone can try.' },
  { id: 'sol-handwash', cat: 'sol', title: 'Foot-pedal hand-wash station',
    hook: 'There is nowhere to wash muddy hands in the garden.',
    make: 'A hands-free hand-wash station worked by a foot pedal, with soap on a rope and a gravel soak-away underneath.' },
  { id: 'sol-cablecar', cat: 'sol', title: 'Garden cable car',
    hook: 'Notes, tools and snacks get carried back and forth all day.',
    make: 'A rope-line cable car with a pulley and a brake that delivers a basket from one spot to another.' },
  { id: 'sol-cooler', cat: 'sol', title: 'Snack-day cooler',
    hook: 'Drinks and fruit go warm by mid-morning on hot days.',
    make: 'An insulated cooler box, tested against others, that keeps ice frozen for a whole LifeHub day.' },
  { id: 'sol-sundial', cat: 'sol', title: 'Garden sundial',
    hook: 'Outdoors, nobody knows the time without going back inside.',
    make: 'A large sundial on the ground where you stand as the pointer, marked hour by hour by checking your shadow all month.' },
  { id: 'sol-seedlibrary', cat: 'sol', title: 'Seed library',
    hook: 'Every season, new seeds are bought while the garden’s own seeds go to waste.',
    make: 'Seeds collected, dried and packed in labelled packets, stored in a home-made seed cabinet anyone can borrow from.' },
  { id: 'sol-boardgames', cat: 'sol', title: 'Rainy-day games café',
    hook: 'When the monsoon keeps everyone indoors at recess, there is little to do.',
    make: 'Three original board games, designed, made and play-tested until they’re fun, and a games corner to keep them in.' }
];
