/* Term 3 Quests — the build pool: 50 ideas the groups choose from.
   Each idea is only a name, what it is, the idea behind it, what the group ends up
   with and a level (1 easier, 2 medium, 3 harder); the plan, roles and
   checkpoints are worked out once a group picks. */
window.T3_POOL = [
  /* ---------- Science in action ---------- */
  { id: 'sci-breakfast', cat: 'sci', level: 3, title: 'Breakfast machine',
    what: "A row of small contraptions lined up so each one sets off the next: a marble rolls, knocks a domino, the last domino tips a cup, and so on, until something useful happens at the very end.",
    hook: 'Energy passes from one thing to the next: rolling, falling, toppling, lifting.',
    make: 'A chain-reaction contraption with at least 10 steps that starts with one marble and ends by pouring a bowl of cereal.' },
  { id: 'sci-claw', cat: 'sci', level: 3, title: 'Hydraulic claw arcade game',
    what: "Like the claw game at a fun fair, but powered by water. Each syringe on the controls is joined by a tube to a syringe on the machine; push one in and the other pushes out, moving the arm or closing the claw.",
    hook: 'Water can’t be squashed, so a push on one syringe moves another at the end of a tube.',
    make: 'A playable claw machine in a box, worked by syringes of coloured water, that grabs prizes for visitors.' },
  { id: 'sci-pinball', cat: 'sci', level: 3, title: 'Cardboard pinball table',
    what: "A tabletop game where you launch a ball up a sloping board and keep it bouncing off bumpers and ramps with two flippers at the bottom. Every hit scores points.",
    hook: 'Angles, springs and slopes decide where a ball goes and how fast.',
    make: 'A full pinball table with a spring launcher, rubber-band flippers, bumpers, ramps and a working score board.' },
  { id: 'sci-automaton', cat: 'sci', level: 3, title: 'Moving story automaton',
    what: "A moving model, like an old mechanical toy. Under the scene, odd-shaped wheels on a turning rod push sticks up and down, so turning one handle makes the figures on top move.",
    hook: 'Cams, cranks and levers turn one turning handle into all kinds of movement.',
    make: 'A hand-cranked wooden or cardboard scene, like a fisherman casting or a dancer turning, where every figure moves.' },
  { id: 'sci-rocket', cat: 'sci', level: 2, title: 'Water rocket launch programme',
    what: "An empty fizzy-drink bottle, partly filled with water and pumped full of air with a bicycle pump. When the cork pops out, the water gushes out of the bottom and the bottle shoots into the sky.",
    hook: 'Air pushes water out of the back, and the water pushes the rocket forwards.',
    make: 'Bottle rockets and a launch pad, tested launch after launch until one flies straight and lands furthest.' },
  { id: 'sci-bridge', cat: 'sci', level: 2, title: 'Craft-stick bridge challenge',
    what: "A model bridge built from ice-cream sticks and glue, laid across a gap between two tables. A bucket hangs from the middle and water is added until it breaks; then you build a better one.",
    hook: 'Triangles can’t change shape, which is why real bridges are built from them.',
    make: 'A bridge of craft sticks and glue that spans a gap between two tables and holds a bucket of water many times its own weight.' },
  { id: 'sci-quake', cat: 'sci', level: 2, title: 'Earthquake-proof city',
    what: "A shake table is a board on rollers that you shake to make a mini earthquake. You build towers on it and find out which designs stay standing.",
    hook: 'Buildings survive shaking when they are braced, balanced and anchored well.',
    make: 'A shake table and a model city of towers that stay standing while it shakes harder and harder.' },
  { id: 'sci-lander', cat: 'sci', level: 1, title: 'Egg-drop Mars lander',
    what: "A protective capsule for an egg. You design a container with a parachute, padding or legs, drop it from a height, and the egg has to survive the landing.",
    hook: 'Slowing a fall gently spreads the force of landing over time.',
    make: 'A lander with a parachute and padding that drops from the first floor and lands a raw egg without a crack.' },
  { id: 'sci-kites', cat: 'sci', level: 2, title: 'Kite workshop and flying day',
    what: "Design and make your own kites from paper, sticks and string, try different shapes and tails, and find out which one flies best.",
    hook: 'A kite flies when the wind pushes up on it more than gravity pulls it down.',
    make: 'Three different kites designed, built and tested, ending in a kite-flying day where the best design flies highest.' },
  { id: 'sci-vortex', cat: 'sci', level: 1, title: 'Air vortex cannon range',
    what: "A box with a round hole at one end and a stretchy sheet at the other. Tap the sheet and a ring of air shoots out of the hole, strong enough to knock over paper cups across the room.",
    hook: 'A sharp push of air rolls into a spinning ring that travels a long way.',
    make: 'A cannon that fires invisible rings of air across the room to knock down paper-cup towers, with a target range for visitors.' },
  { id: 'sci-lightmaze', cat: 'sci', level: 2, title: 'Light maze',
    what: "A box maze you play with a torch. Small mirrors inside bounce the beam around corners, and you angle them so the light reaches the target at the end.",
    hook: 'Light bounces off a mirror at the same angle it hits it.',
    make: 'A dark maze box where players steer a torch beam with angled mirrors past obstacles to hit a target.' },
  { id: 'sci-camera', cat: 'sci', level: 2, title: 'Walk-in pinhole camera',
    what: "A pinhole camera is a dark box with a tiny hole in one side. Light from outside comes through the hole and paints a picture of the world on the opposite inside wall, upside down. Make the box big enough and you can put your head inside to watch it.",
    hook: 'Light travels in straight lines, so a tiny hole projects the world upside down.',
    make: 'A blacked-out box big enough to put your head and shoulders in, that shows the garden outside upside down on a screen.' },
  { id: 'sci-shadow', cat: 'sci', level: 1, title: 'Shadow puppet theatre',
    what: "A small theatre with a white cloth screen and a lamp behind it. Cardboard puppets on sticks, held between the lamp and the screen, cast shadows that the audience watches from the front.",
    hook: 'Shadows grow and shrink as objects move closer to or further from the light.',
    make: 'A shadow theatre with jointed puppets and sliding scenery, and a short show performed for the other groups.' },
  { id: 'sci-junkband', cat: 'sci', level: 1, title: 'Junk band',
    what: "Musical instruments made from everyday things, like rubber bands stretched over a box, straws cut to different lengths and bottles with different amounts of water, each tuned to play real notes.",
    hook: 'Every sound is a vibration; length, tightness and size change the note.',
    make: 'A set of tuned instruments from everyday things, like a rubber-band guitar, straw pan pipes and a water-bottle xylophone, played as a band.' },
  { id: 'sci-crane', cat: 'sci', level: 2, title: 'Scrapyard magnet crane',
    what: "An electromagnet is a nail wrapped in wire that becomes a magnet only when a battery is connected. On the end of a model crane, it picks up metal things and drops them when you switch it off.",
    hook: 'Electricity flowing through a coil of wire makes a magnet you can switch on and off.',
    make: 'A crane with a hand winch and a battery electromagnet that picks up and drops a load of paper clips on command.' },
  { id: 'sci-trebuchet', cat: 'sci', level: 2, title: 'Trebuchet target challenge',
    what: "A trebuchet is a giant catapult from castle times. A heavy weight drops on one end of an arm, and the other end swings up and flings a ball far away. You build a tabletop one.",
    hook: 'A falling weight swings an arm and flings a ball much further than a throw.',
    make: 'A tabletop trebuchet tuned to hit targets at different distances, every time.' },
  { id: 'sci-turbine', cat: 'sci', level: 3, title: 'Wind turbine power station',
    what: "A small windmill that makes electricity. When its blades spin, they turn a little motor, and a spinning motor makes enough electricity to light a small bulb.",
    hook: 'Blades turn the wind into spinning, and a motor turned backwards makes electricity.',
    make: 'A turbine with blades the group designs, that lights an LED in front of a fan and shows its voltage on a meter.' },
  { id: 'sci-waterwheel', cat: 'sci', level: 2, title: 'Water wheel that does work',
    what: "A wheel with paddles or cups round its edge. Put it under running water and it turns, and as it turns it winds up a string and lifts something.",
    hook: 'Falling water has energy that a wheel can catch and use.',
    make: 'A water wheel under a running tap that winds up a string and lifts a small load, as heavy as it can manage.' },
  { id: 'sci-archimedes', cat: 'sci', level: 2, title: 'Archimedes screw',
    what: "A tube wound round and round a pole in a spiral. Put the bottom in water and turn the pole, and the water climbs up the spiral and pours out at the top.",
    hook: 'A turning spiral can carry water uphill, a trick over 2,000 years old.',
    make: 'A hand-turned screw made from clear tubing wound round a pole that lifts water from one tub to a higher one.' },
  { id: 'sci-orrery', cat: 'sci', level: 3, title: 'Hand-cranked solar system',
    what: "A model of the Sun, Earth and Moon joined by cardboard gear wheels. Turn the handle and the Earth goes round the Sun while the Moon goes round the Earth, just as they do in space.",
    hook: 'Gears of different sizes turn at different speeds, like planets and moons.',
    make: 'A cardboard gear model where turning one handle moves the Earth round the Sun and the Moon round the Earth.' },
  { id: 'sci-dome', cat: 'sci', level: 3, title: 'Newspaper dome planetarium',
    what: "A round, igloo-shaped shelter made by rolling newspaper into tubes and taping them into triangles. Inside, a home-made star projector lights up the ceiling with stars.",
    hook: 'A dome made of triangles is light but very strong.',
    make: 'A dome of rolled newspaper big enough for the group to sit inside, with a home-made star projector lighting up the ceiling.' },
  { id: 'sci-hand', cat: 'sci', level: 2, title: 'Robotic hand',
    what: "A model hand made from cardboard. Strings run along each finger like the tendons in your arm; pull a string and that finger bends, so the hand can grab things.",
    hook: 'Tendons pull on bones to bend fingers.',
    make: 'A life-size cardboard hand with string tendons and straw joints that bends each finger and can grip a cup.' },
  { id: 'sci-pendulum', cat: 'sci', level: 1, title: 'Pendulum painting machine',
    what: "A pendulum is a weight swinging on a string. Here the weight is a cup of paint with a small hole in the bottom, swinging over paper, so it drips swirly patterns as it swings.",
    hook: 'A swinging pendulum traces patterns that depend on its length and push.',
    make: 'A frame with a dripping paint pendulum that makes swirling patterns, and a gallery of the best ones.' },
  { id: 'sci-bubbles', cat: 'sci', level: 1, title: 'Giant bubble lab',
    what: "Mix and test your own bubble liquid to find the best recipe, then make giant wands from string and sticks to blow enormous bubbles.",
    hook: 'A bubble is a thin skin of water held together by surface tension.',
    make: 'Tested bubble recipes and home-made giant wands, ending in a bubble show with bubbles big enough to stand inside.' },
  { id: 'sci-waterclock', cat: 'sci', level: 2, title: 'Water clock',
    what: "Before watches, people told the time with dripping water. Water drips slowly from one bottle into another, and marks on the bottle show how many minutes have passed.",
    hook: 'Before clocks had springs, people measured time with dripping water.',
    make: 'A clock of stacked bottles that drips through and marks the minutes, tested against a stopwatch until it’s accurate.' },

  /* ---------- Solve a LifeHub problem ---------- */
  { id: 'sol-den', cat: 'sol', level: 3, title: 'Bamboo reading den',
    what: "A small hut made of bamboo poles tied together with rope, with shade cloth on top: a cool, quiet place to read outside.",
    hook: 'There is no quiet, shady spot outside to read, think or talk.',
    make: 'A bamboo den lashed together with rope, roofed with shade net, big enough for four Risers to sit inside.' },
  { id: 'sol-dryer', cat: 'sol', level: 3, title: 'Solar food dryer',
    what: "A box with a clear plastic window that traps the sun’s heat. Warm air flows through trays of sliced fruit or leaves and dries them, while keeping flies and dust out.",
    hook: 'Extra fruit and leaves go to waste, and drying them in the open brings dust and flies.',
    make: 'A sun-powered dryer box with mesh trays that dries fruit and curry leaves faster and cleaner than the open air.' },
  { id: 'sol-vgarden', cat: 'sol', level: 2, title: 'Bottle tower garden',
    what: "Plastic bottles cut open and hung one above another on a wall or fence, filled with soil and plants. Water poured in at the top trickles down through each bottle in turn.",
    hook: 'There is little ground space to grow food, and pots get forgotten.',
    make: 'Bottle planters hung in columns that water each other from one bucket at the top, growing herbs and greens for the kitchen.' },
  { id: 'sol-weather', cat: 'sol', level: 2, title: 'LifeHub weather station',
    what: "Simple instruments you make yourself: a bottle that measures rain, an arrow that shows the wind’s direction and spinning cups that show how strong it is. You read them every day and post the results.",
    hook: 'Watering the garden and going outdoors are decided by guessing the weather.',
    make: 'Home-made rain gauge, wind vane and wind meter, and a daily weather board that tells the garden team whether to water.' },
  { id: 'sol-ecobench', cat: 'sol', level: 3, title: 'Ecobrick bench',
    what: "An ecobrick is a plastic bottle stuffed so tightly with clean plastic waste that it’s as hard as a brick. Lots of ecobricks, stacked and covered in mud, make a strong bench.",
    hook: 'Snack wrappers and plastic bags pile up with nowhere to go.',
    make: 'Bottles packed hard with plastic waste, built into a mud-covered bench in the garden.' },
  { id: 'sol-steppingstones', cat: 'sol', level: 2, title: 'Stepping-stone path',
    what: "Mix cement, pour it into moulds like old trays or buckets, press in tiles, pebbles or handprints, and let it set. Then lay the stones as a path.",
    hook: 'One corner of the garden turns to mud every time it rains.',
    make: 'Hand-poured concrete stepping stones decorated with mosaic and handprints, laid as a path across the muddy patch.' },
  { id: 'sol-herbspiral', cat: 'sol', level: 2, title: 'Herb spiral',
    what: "A garden bed built as a snail-shell spiral of bricks that rises in the middle. The top stays sunny and dry and the bottom stays damp, so each herb gets the spot it likes.",
    hook: 'The kitchen buys herbs that could be grown right outside.',
    make: 'A raised spiral bed of bricks and soil with sunny dry herbs at the top and thirsty ones at the bottom.' },
  { id: 'sol-insecthotel', cat: 'sol', level: 1, title: 'Insect hotel',
    what: "A stack of crates filled with hollow sticks, bricks with holes, bark and pine cones: little hiding places where helpful insects can live.",
    hook: 'The garden needs bees, ladybirds and other helpers, but has nowhere for them to live.',
    make: 'A tall bug hotel of crates packed with bamboo, bricks, bark and pine cones, and a log of who moves in.' },
  { id: 'sol-birdscarer', cat: 'sol', level: 1, title: 'Seedling guard',
    what: "Crows and squirrels are put off by things that move, flash or make noise. You build spinning, shiny and rattling scarers and covers, and test which work best.",
    hook: 'Crows and squirrels dig up and eat the seedlings.',
    make: 'Moving, flashing, rattling bird scarers and seedling covers, tested to see which really keep the beds safe.' },
  { id: 'sol-birdcafe', cat: 'sol', level: 1, title: 'Bird café',
    what: "A feeding and drinking spot for birds, with a feeder, a shallow water bowl and perches, placed where you can watch who visits.",
    hook: 'In the hot months birds struggle to find water and food.',
    make: 'A bird feeder, water bowl and perch station placed where everyone can watch, and a bird-spotting chart of every visitor.' },
  { id: 'sol-compost', cat: 'sol', level: 1, title: 'Snack-waste compost',
    what: "Compost is rich soil made from rotting food scraps and leaves. You build a bin for LifeHub’s peels and leftovers, and a worm box where worms speed up the job.",
    hook: 'Fruit peels and leftovers go into the bin while the garden needs soil.',
    make: 'A compost bay with a worm bin that turns LifeHub’s food scraps into rich soil for the garden.' },
  { id: 'sol-mosquito', cat: 'sol', level: 2, title: 'Mosquito patrol',
    what: "Mosquitoes lay their eggs in still water. You search LifeHub for every spot where water collects, fix each one, and set simple traps that show whether mosquitoes are still laying eggs.",
    hook: 'In the monsoon, mosquitoes breed in any water left standing.',
    make: 'A map of every place water collects at LifeHub, a fix for each one, and egg traps that show if the fixes are working.' },
  { id: 'sol-arcade', cat: 'sol', level: 2, title: 'Cardboard arcade',
    what: "A games arcade made entirely from cardboard boxes, with ball throws, mazes, hoops and ball drops, plus tickets and small prizes, for everyone to play at a LifeHub event.",
    hook: 'LifeHub events need something fun that also raises money.',
    make: 'An arcade of cardboard games, from basketball hoops to ball drops, with tickets and prizes, run at a LifeHub event.' },
  { id: 'sol-paper', cat: 'sol', level: 1, title: 'Recycled paper studio',
    what: "Old paper is soaked, blended into mush, spread thin on a screen and dried into fresh new sheets. You make the screens and turn the paper into notebooks and cards.",
    hook: 'Piles of used paper get thrown away every week.',
    make: 'Home-made frames and screens to turn waste paper into new sheets, made into LifeHub notebooks and cards.' },
  { id: 'sol-dye', cat: 'sol', level: 1, title: 'Natural dye studio',
    what: "Turmeric, beetroot and onion skins boiled in water make coloured dyes. You test which colours stay after washing, then dye T-shirts with patterns.",
    hook: 'LifeHub has no team T-shirts for events and outings.',
    make: 'Dyes from turmeric, beetroot and onion skins, tested for colour and fastness, used to tie-dye a T-shirt for everyone.' },
  { id: 'sol-library', cat: 'sol', level: 3, title: 'Little library',
    what: "A small cupboard with a door, fixed near the entrance, where anyone can leave a book or borrow one.",
    hook: 'Good books sit unread at home while others have run out of things to read.',
    make: 'A weatherproof book box with a door at the LifeHub entrance, and a simple borrow-and-return system.' },
  { id: 'sol-furniture', cat: 'sol', level: 2, title: 'Cardboard furniture',
    what: "Cardboard is surprisingly strong when it’s folded and layered the right way. You design stools and a bench made only of cardboard and glue.",
    hook: 'The reading corner needs more seats, and there is a pile of cardboard boxes.',
    make: 'Stools and a bench made only of cardboard and glue that are strong enough for an adult to sit on.' },
  { id: 'sol-hammock', cat: 'sol', level: 3, title: 'Rope hammock',
    what: "A hammock is a hanging bed made of rope net. You learn the knots, tie a net strong enough to lie in, and hang it between two strong points.",
    hook: 'There is nowhere to lie back and rest during a long day.',
    make: 'A hammock or hanging chair knotted from rope, strong enough to hold a grown-up, hung in a shady spot.' },
  { id: 'sol-obstacle', cat: 'sol', level: 2, title: 'Recess obstacle course',
    what: "A course of things to climb over, crawl under, balance on and jump through, built from tyres, crates, ropes and planks, with a stopwatch challenge.",
    hook: 'Recess games get repetitive and the same few things get played every day.',
    make: 'A course of tyres, crates, ropes and planks with a timed challenge everyone can try.' },
  { id: 'sol-handwash', cat: 'sol', level: 2, title: 'Foot-pedal hand-wash station',
    what: "A container of water on a stand that tips when you press a pedal with your foot, so you can wash your hands without touching anything.",
    hook: 'There is nowhere to wash muddy hands in the garden.',
    make: 'A hands-free hand-wash station worked by a foot pedal, with soap on a rope and a gravel soak-away underneath.' },
  { id: 'sol-cablecar', cat: 'sol', level: 3, title: 'Garden cable car',
    what: "A rope stretched between two points with a pulley wheel running along it. A basket hangs from the pulley and travels along the rope, with a way to stop it at the end.",
    hook: 'Notes, tools and snacks get carried back and forth all day.',
    make: 'A rope-line cable car with a pulley and a brake that delivers a basket from one spot to another.' },
  { id: 'sol-cooler', cat: 'sol', level: 1, title: 'Snack-day cooler',
    what: "A box lined with materials that keep heat out, like newspaper, cloth, foam or straw. You test which design keeps a block of ice frozen longest.",
    hook: 'Drinks and fruit go warm by mid-morning on hot days.',
    make: 'An insulated cooler box, tested against others, that keeps ice frozen for a whole LifeHub day.' },
  { id: 'sol-sundial', cat: 'sol', level: 1, title: 'Garden sundial',
    what: "A sundial tells the time by shadows. Here you are the pointer: stand on a marked spot and your shadow points to the hour marked on the ground.",
    hook: 'Outdoors, nobody knows the time without going back inside.',
    make: 'A large sundial on the ground where you stand as the pointer, marked hour by hour by checking your shadow all month.' },
  { id: 'sol-seedlibrary', cat: 'sol', level: 1, title: 'Seed library',
    what: "Plants make seeds that can grow new plants. You collect seeds from the garden, dry them, pack them in labelled envelopes and keep them in a cabinet people can borrow from.",
    hook: 'Every season, new seeds are bought while the garden’s own seeds go to waste.',
    make: 'Seeds collected, dried and packed in labelled packets, stored in a home-made seed cabinet anyone can borrow from.' },
  { id: 'sol-boardgames', cat: 'sol', level: 2, title: 'Rainy-day games café',
    what: "Invent your own board games, with the board, pieces, cards and rules, and test them with others until they’re really fun to play.",
    hook: 'When the monsoon keeps everyone indoors at recess, there is little to do.',
    make: 'Three original board games, designed, made and play-tested until they’re fun, and a games corner to keep them in.' }
];
