/* Term 3 Quests — the build pool: 50 ideas the groups choose from.
   Each idea is only a name, what it is, the idea behind it, what the group
   ends up with and a level (1 easier, 2 medium, 3 harder); the plan, roles
   and checkpoints are worked out once a group picks. Written in very
   simple English so every Riser can read it. */
window.T3_POOL = [
  /* ---------- Science in action ---------- */
  { id: 'sci-breakfast', cat: 'sci', level: 3, title: 'Breakfast machine',
    what: 'A long line of small tricks. A marble rolls and hits a block. The block falls and pushes a car. Each thing starts the next thing. At the end, the machine pours cereal into a bowl.',
    hook: 'One small push can pass from thing to thing, all the way down the line.',
    make: 'A machine with 10 or more steps that pours a bowl of cereal by itself.' },
  { id: 'sci-claw', cat: 'sci', level: 3, title: 'Water claw game',
    what: 'Like the claw game at a fair, but it runs on water. Two syringes are joined by a tube. Push one, and the other one moves. This makes the arm go up and down and the claw open and close.',
    hook: 'Water can not be squashed. So a push at one end comes out at the other end.',
    make: 'A claw game in a box that picks up small prizes. Visitors can play it.' },
  { id: 'sci-pinball', cat: 'sci', level: 3, title: 'Cardboard pinball',
    what: 'A table game. You shoot a ball up a slope. The ball bounces off bumpers and rolls back down. You hit it back up with two flippers. Each bump gives you points.',
    hook: 'Slopes, bumps and springs change where a ball goes and how fast.',
    make: 'A pinball table with a ball shooter, flippers, bumpers and a score board.' },
  { id: 'sci-automaton', cat: 'sci', level: 3, title: 'Moving toy scene',
    what: 'A small scene with people or animals on top of a box. Inside the box are odd-shaped wheels on a stick. Turn the handle, and the wheels push the people up and down so they move.',
    hook: 'One turning handle can make many different moves.',
    make: 'A box scene, like a man fishing or a girl dancing, that moves when you turn the handle.' },
  { id: 'sci-rocket', cat: 'sci', level: 2, title: 'Water rocket',
    what: 'A big soft-drink bottle with some water in it. You pump air in with a bicycle pump. The cork pops out. The water shoots down, and the bottle flies up into the sky.',
    hook: 'When the water pushes down, the rocket goes up.',
    make: 'Bottle rockets and a stand to launch them from. You change them until one flies straight and far.' },
  { id: 'sci-bridge', cat: 'sci', level: 2, title: 'Stick bridge',
    what: 'A bridge made of ice-cream sticks and glue. It goes across a gap between two tables. You hang a bucket from it and add water, cup by cup. How much can it hold before it breaks?',
    hook: 'Triangles do not bend out of shape. That is why bridges use them.',
    make: 'A stick bridge that holds a big bucket of water.' },
  { id: 'sci-quake', cat: 'sci', level: 2, title: 'Earthquake city',
    what: 'A board that you shake to make a pretend earthquake. You build towers on it. Then you shake it and see which towers stay up.',
    hook: 'Some buildings fall in a shake. Some stay up. The shape makes the difference.',
    make: 'A shaking board and a small city of towers that do not fall down.' },
  { id: 'sci-lander', cat: 'sci', level: 1, title: 'Egg drop',
    what: 'You build a little space pod for a raw egg. You drop it from up high. The egg must not break.',
    hook: 'If you slow a fall down, the landing is soft.',
    make: 'A pod with a parachute and soft padding that keeps an egg safe from a big drop.' },
  { id: 'sci-kites', cat: 'sci', level: 2, title: 'Kite making',
    what: 'You make kites with paper, sticks and string. You try different shapes and tails. Then you fly them and see which one flies best.',
    hook: 'The wind pushes the kite up. The string holds it in place.',
    make: 'Three kites you made and tested, and a kite-flying day at the end.' },
  { id: 'sci-vortex', cat: 'sci', level: 1, title: 'Air cannon',
    what: 'A box with a round hole on one side. You tap the back of the box. A ring of air shoots out of the hole. You can not see it, but it can knock over paper cups far away.',
    hook: 'A quick push of air can travel a long way.',
    make: 'An air cannon and a game where you knock down towers of cups.' },
  { id: 'sci-lightmaze', cat: 'sci', level: 2, title: 'Light maze',
    what: 'A box maze you play with a torch. Little mirrors inside bounce the light around corners. You turn the mirrors so the light reaches the end.',
    hook: 'Light bounces off a mirror, like a ball off a wall.',
    make: 'A dark maze box with mirrors. Players move the mirrors to light up the target.' },
  { id: 'sci-camera', cat: 'sci', level: 1, title: 'Head-box camera',
    what: 'A big dark box you wear over your head. A tiny hole on one side lets light in. You look through a second hole underneath at a white sheet inside. The view behind you shows up on the sheet, upside down.',
    hook: 'Light goes in straight lines. A tiny hole turns the picture upside down.',
    make: 'A big box you can wear, that shows the garden on a white sheet inside.' },
  { id: 'sci-shadow', cat: 'sci', level: 1, title: 'Shadow puppet show',
    what: 'A small stage with a white cloth and a lamp behind it. You hold paper puppets on sticks in front of the lamp. People in front see the shadows move on the cloth.',
    hook: 'Move a puppet near the lamp and its shadow grows. Move it away and it shrinks.',
    make: 'A shadow stage, puppets with moving arms and legs, and a short show.' },
  { id: 'sci-junkband', cat: 'sci', level: 1, title: 'Junk band',
    what: 'Music made from things at home. Rubber bands on a box make a guitar. Straws of different lengths make a flute. Bottles with different amounts of water make a xylophone.',
    hook: 'Every sound is a shake. Long, short, tight or loose changes the note.',
    make: 'A set of home-made instruments, and a song you play as a band.' },
  { id: 'sci-crane', cat: 'sci', level: 2, title: 'Magnet crane',
    what: 'A model crane with a magnet at the end. The magnet is a nail wrapped in wire with a battery. When it is switched on, it picks up metal things. When it is switched off, it drops them.',
    hook: 'Electricity in a coil of wire can make a magnet.',
    make: 'A crane that lifts and drops paper clips when you switch it on and off.' },
  { id: 'sci-trebuchet', cat: 'sci', level: 2, title: 'Castle catapult',
    what: 'A catapult from castle times. A heavy weight drops down on one end. The other end swings up fast and throws a ball far away.',
    hook: 'A falling weight can throw a ball much farther than your arm.',
    make: 'A table-top catapult that hits targets near and far.' },
  { id: 'sci-turbine', cat: 'sci', level: 3, title: 'Wind power',
    what: 'A small windmill. When the wind spins the blades, they turn a tiny motor. The spinning motor makes electricity and lights up a small bulb.',
    hook: 'Spinning a motor makes electricity.',
    make: 'A windmill with blades you design, that lights a bulb in front of a fan.' },
  { id: 'sci-waterwheel', cat: 'sci', level: 2, title: 'Water wheel',
    what: 'A wheel with cups all around it. You put it under a running tap. The water turns the wheel. As it turns, it pulls up a string and lifts a small load.',
    hook: 'Moving water can push things and do work for us.',
    make: 'A water wheel that lifts a small bag as heavy as it can.' },
  { id: 'sci-archimedes', cat: 'sci', level: 2, title: 'Water climber',
    what: 'A see-through tube wound round and round a stick, like a slide. Put the bottom in water and turn the stick. The water climbs up the tube and comes out at the top.',
    hook: 'A turning spiral can carry water uphill. People found this out over 2,000 years ago.',
    make: 'A water climber that moves water from a low tub to a high tub.' },
  { id: 'sci-orrery', cat: 'sci', level: 3, title: 'Sun, Earth and Moon machine',
    what: 'A model of the Sun, Earth and Moon. Cardboard gear wheels join them. Turn the handle, and the Earth goes round the Sun. The Moon goes round the Earth too.',
    hook: 'Big and small gear wheels turn at different speeds.',
    make: 'A turning model of the Sun, Earth and Moon.' },
  { id: 'sci-dome', cat: 'sci', level: 3, title: 'Newspaper star dome',
    what: 'A round hut, like an igloo, made from rolled-up newspaper sticks taped into triangles. Inside, you shine a home-made star light on the roof to make a night sky.',
    hook: 'Triangles make a strong shape, even from paper.',
    make: 'A paper dome the group can sit in, with stars on the roof.' },
  { id: 'sci-hand', cat: 'sci', level: 2, title: 'Robot hand',
    what: 'A cardboard hand. Strings run along each finger. Pull a string, and that finger bends. Pull them all, and the hand can grab things.',
    hook: 'Your fingers bend because strings inside your arm pull on them.',
    make: 'A big cardboard hand that can pick up a cup.' },
  { id: 'sci-pendulum', cat: 'sci', level: 1, title: 'Swinging paint machine',
    what: 'A cup of paint hangs on a string. It has a tiny hole in the bottom. You swing it over paper. The paint drips out and makes swirly patterns.',
    hook: 'A swinging thing makes a pattern. Change the string and the pattern changes.',
    make: 'A swinging paint machine and a wall of the best paintings.' },
  { id: 'sci-bubbles', cat: 'sci', level: 1, title: 'Giant bubbles',
    what: 'You mix your own bubble water and test which mix works best. Then you make giant bubble wands from sticks and string.',
    hook: 'A bubble is a very thin skin of soapy water.',
    make: 'The best bubble mix, giant wands, and a bubble show.' },
  { id: 'sci-waterclock', cat: 'sci', level: 2, title: 'Water clock',
    what: 'A clock with no batteries. Water drips slowly from one bottle into another. Lines on the bottle show how many minutes have passed.',
    hook: 'Long ago, people used dripping water to tell the time.',
    make: 'A water clock that keeps time as well as a stopwatch.' },

  /* ---------- Solve a LifeHub problem ---------- */
  { id: 'sol-den', cat: 'sol', level: 3, title: 'Bamboo reading hut',
    what: 'A small hut made of bamboo poles. The poles are tied together with rope. A shade cloth goes on top. It is a cool, quiet place to read outside.',
    hook: 'We have no quiet, shady place outside to read or rest.',
    make: 'A bamboo hut big enough for four children to sit inside.' },
  { id: 'sol-dryer', cat: 'sol', level: 3, title: 'Sun dryer',
    what: 'A box with a clear plastic top. The sun makes it hot inside. You put fruit slices and leaves on trays inside, and the heat dries them. Flies and dust can not get in.',
    hook: 'Extra fruit and leaves go to waste. Drying them outside brings flies and dust.',
    make: 'A sun dryer box that dries fruit and curry leaves.' },
  { id: 'sol-vgarden', cat: 'sol', level: 2, title: 'Bottle garden',
    what: 'Plastic bottles cut open and hung one above the other on a fence. Each bottle has soil and a plant. Water goes in at the top and drips down from bottle to bottle.',
    hook: 'We do not have much ground to grow plants.',
    make: 'A wall of bottle plants that all get water from one bucket.' },
  { id: 'sol-weather', cat: 'sol', level: 2, title: 'Weather station',
    what: 'Tools you make to check the weather. A bottle catches rain. An arrow shows where the wind comes from. Spinning cups show how strong the wind is. You check them every day.',
    hook: 'We guess the weather when we plan to water the garden or go outside.',
    make: 'Weather tools and a board that tells everyone today’s weather.' },
  { id: 'sol-ecobench', cat: 'sol', level: 3, title: 'Plastic bottle bench',
    what: 'You push clean plastic wrappers into bottles until they are hard like bricks. Then you stack the bottle bricks and cover them with mud to make a bench.',
    hook: 'Wrappers and plastic bags pile up and have nowhere to go.',
    make: 'A strong bench in the garden made from bottle bricks and mud.' },
  { id: 'sol-steppingstones', cat: 'sol', level: 2, title: 'Stepping stones',
    what: 'You mix cement and pour it into old trays or tubs. You press in tiles, pebbles or your handprint. When it is hard, you take it out. Then you lay the stones in a line.',
    hook: 'One part of the garden gets very muddy when it rains.',
    make: 'A path of pretty stepping stones across the mud.' },
  { id: 'sol-herbspiral', cat: 'sol', level: 2, title: 'Snail-shell garden',
    what: 'A garden bed shaped like a snail shell. It is made of bricks and soil and goes up high in the middle. The top is sunny and dry. The bottom is wet. Each plant gets the spot it likes.',
    hook: 'We buy herbs for the kitchen that we could grow ourselves.',
    make: 'A snail-shell garden full of herbs for the kitchen.' },
  { id: 'sol-insecthotel', cat: 'sol', level: 1, title: 'Bug hotel',
    what: 'A stack of boxes filled with sticks, bricks with holes, bark and pine cones. Small bugs like bees and ladybirds can live in the little gaps.',
    hook: 'Good bugs help the garden, but they have no place to live.',
    make: 'A tall bug hotel and a chart of the bugs that move in.' },
  { id: 'sol-birdscarer', cat: 'sol', level: 1, title: 'Bird scarer',
    what: 'Crows and squirrels do not like things that spin, shine or rattle. You make scarers that do all three. Then you see which ones keep the birds away.',
    hook: 'Crows and squirrels dig up and eat our baby plants.',
    make: 'Spinning, shiny and noisy scarers that keep the baby plants safe.' },
  { id: 'sol-birdcafe', cat: 'sol', level: 1, title: 'Bird café',
    what: 'A place where birds can eat and drink. It has a food holder, a water bowl and places to sit. You put it where you can watch the birds come.',
    hook: 'In hot weather, birds find it hard to get food and water.',
    make: 'A bird café and a chart of every bird that visits.' },
  { id: 'sol-compost', cat: 'sol', level: 1, title: 'Compost bin',
    what: 'Fruit peels and old leaves rot and turn into rich soil. This is called compost. You make a bin for our food scraps, and a box where worms help make the soil.',
    hook: 'Fruit peels go in the bin, but the garden needs good soil.',
    make: 'A compost bin and a worm box that turn our scraps into soil.' },
  { id: 'sol-mosquito', cat: 'sol', level: 2, title: 'Mosquito hunt',
    what: 'Mosquitoes lay eggs in still water. You look all around LifeHub for places where water sits. You fix each one. Then you set little traps to check if mosquitoes are still laying eggs.',
    hook: 'In the rainy season, mosquitoes grow in water that is left standing.',
    make: 'A map of every wet spot, a fix for each one, and traps to check it worked.' },
  { id: 'sol-arcade', cat: 'sol', level: 2, title: 'Cardboard game fair',
    what: 'Fun games made from cardboard boxes. You can throw balls into hoops, roll balls through mazes, and win tickets and small prizes.',
    hook: 'LifeHub events need fun things to do that can also raise money.',
    make: 'A cardboard game fair for a LifeHub event.' },
  { id: 'sol-paper', cat: 'sol', level: 1, title: 'Paper making',
    what: 'You soak old paper in water and mash it into mush. You spread it thin on a screen and let it dry. It becomes a new sheet of paper.',
    hook: 'We throw away a lot of used paper every week.',
    make: 'New paper made from old paper, turned into notebooks and cards.' },
  { id: 'sol-dye', cat: 'sol', level: 1, title: 'Colour from plants',
    what: 'You boil turmeric, beetroot and onion skins in water. The water turns into colour. You test which colours stay after washing. Then you colour T-shirts with them.',
    hook: 'We have no team T-shirts for trips and events.',
    make: 'A coloured T-shirt for everyone, made with plant colours.' },
  { id: 'sol-library', cat: 'sol', level: 3, title: 'Little library',
    what: 'A small cupboard with a door near the front gate. Anyone can put a book in or take a book out to read.',
    hook: 'Good books sit at home and no one reads them.',
    make: 'A book cupboard that keeps out rain, and a way to borrow and give back books.' },
  { id: 'sol-furniture', cat: 'sol', level: 2, title: 'Cardboard seats',
    what: 'Cardboard is very strong when you fold it and stack it the right way. You make stools and a bench using only cardboard and glue.',
    hook: 'The reading corner needs more seats, and we have lots of old boxes.',
    make: 'Cardboard stools and a bench strong enough for a grown-up to sit on.' },
  { id: 'sol-hammock', cat: 'sol', level: 3, title: 'Rope hammock',
    what: 'A hammock is a bed made of rope that hangs between two posts. You learn to tie knots and make a rope net strong enough to lie in.',
    hook: 'We have no place to lie down and rest on a long day.',
    make: 'A rope hammock strong enough for a grown-up, hung in the shade.' },
  { id: 'sol-obstacle', cat: 'sol', level: 2, title: 'Obstacle course',
    what: 'A play course with things to climb over, crawl under, walk on and jump through. You use tyres, crates, ropes and planks.',
    hook: 'We play the same few games at break time every day.',
    make: 'An obstacle course and a timed race for everyone.' },
  { id: 'sol-handwash', cat: 'sol', level: 2, title: 'Foot-press hand wash',
    what: 'A water can on a stand. You press a stick with your foot, and the can tips and pours water. You can wash your hands without touching anything.',
    hook: 'There is nowhere to wash muddy hands in the garden.',
    make: 'A hand-wash stand you work with your foot, with soap on a rope.' },
  { id: 'sol-cablecar', cat: 'sol', level: 3, title: 'Rope cable car',
    what: 'A rope tied tight between two places. A wheel rolls along the rope with a basket hanging from it. The basket carries things from one end to the other.',
    hook: 'We carry notes, tools and snacks back and forth all day.',
    make: 'A cable car that carries a basket along a rope and stops at the end.' },
  { id: 'sol-cooler', cat: 'sol', level: 1, title: 'Ice keeper box',
    what: 'A box that keeps the heat out. You line it with things like newspaper, cloth or straw. You test which box keeps ice frozen the longest.',
    hook: 'Our drinks and fruit get warm by the middle of the morning.',
    make: 'A cool box that keeps ice frozen all day.' },
  { id: 'sol-sundial', cat: 'sol', level: 1, title: 'Shadow clock',
    what: 'A clock that uses your shadow. You stand on a spot on the ground. Your shadow points to the time marked on the ground.',
    hook: 'When we are outside, we do not know what time it is.',
    make: 'A big shadow clock on the ground, with the hours marked.' },
  { id: 'sol-seedlibrary', cat: 'sol', level: 1, title: 'Seed library',
    what: 'Plants make seeds, and seeds grow new plants. You collect seeds from the garden, dry them and put them in packets with names. People can take seeds to plant.',
    hook: 'We buy new seeds, but our own plants give us seeds for free.',
    make: 'Seed packets with names and a seed cupboard for everyone.' },
  { id: 'sol-boardgames', cat: 'sol', level: 2, title: 'Rainy-day games',
    what: 'You make up your own board games. You make the board, the pieces, the cards and the rules. Then you play them with friends and make them better.',
    hook: 'When it rains at break time, there is not much to do indoors.',
    make: 'Three new board games and a corner to keep them in.' }
];
